<?php

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\user\UserInterface;
use Drupal\Core\Session\AccountProxyInterface;
use Drupal\Core\Annotation\QueueWorker;

function hello_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {

    // Main module help for the block module.
    case 'help.page.block':
      return '<p>' . t('Blocks are boxes of content rendered into an area, or region, of a web page. The default theme Bartik, for example, implements the regions "Sidebar first", "Sidebar second", "Featured", "Content", "Header", "Footer", etc., and a block may appear in any one of these areas. The <a href=":blocks">blocks administration page</a> provides a drag-and-drop interface for assigning a block to a region, and for controlling the order of blocks within regions.', [
        ':blocks' => \Drupal::url('block.admin_display'),
      ]) . '</p>';

    // Help for another path in the block module.
    case 'block.admin_display':
      return '<p>' . t('This page provides a drag-and-drop interface for assigning a block to a region, and for controlling the order of blocks within regions. Since not all themes implement the same regions, or display regions in the same way, blocks are positioned on a per-theme basis. Remember that your changes will not be saved until you click the <em>Save blocks</em> button at the bottom of the page.') . '</p>';
    
    // Main module help for the block module.
    case 'help.page.hello':
      return '<p>' . t('Help for module Hello.', [
        ':blocks' => \Drupal::url('block.admin_display'),
      ]) . '</p>';
    }
}

  function hello_cron() {
    $time = \Drupal::service('datetime.time')->getCurrentTime();
    $days = \Drupal::config('hello.settings')->get('purge_week_number');
    $date_fin = $time - ($days * 86400);
    \Drupal::database()->delete('hello_user_statistics')
    ->condition('time', $date_fin, '<')
    ->execute();
    // \Drupal::messenger()->addMessage(t('Hello Cron'));
  }

  function hello_user_login(UserInterface $account) {
    $time = \Drupal::service('datetime.time')->getCurrentTime();
    \Drupal::messenger()->addMessage(t('Hello dear %name', ['%name' => $account->getAccountName()]));
    \Drupal::database()->insert('hello_user_statistics')
    ->fields([
      'time' => $time,
      'uid' => $account->id(),
      'action' => 1,
    ])
    ->execute();
  }

  function hello_user_logout(AccountProxyInterface $account) {
    $time = \Drupal::service('datetime.time')->getCurrentTime();
    \Drupal::database()->insert('hello_user_statistics')
    ->fields([
      'time' => $time,
      'uid' => $account->id(),
      'action' => 0,
    ])
    ->execute();
  }

  function hello_theme($existing, $type, $theme, $path){
    return [
      'hello_user_conexion' => [
        'template' => 'hello_user_conexion',
        'variables' => ['user' => NULL, 'count' => NULL],
      ],
    ];

  }

  function hello_page_attachments(array &$page){
    $page['#attached']['library'][] = 'hello/hello.tree';
  }

